### ISSUE TITLE
Crash your browser test case

### ISSUE THREAD

**Issue by dy** [xpl/what-code-is-faster#1]
So this test case crashes my browser, interesting. Is that memory limitation?
```js
let a = Object.create(Array.prototype), b = []

benchmark('Do closures cost anything?', function initialValue() {
  return Math.random()
}, {
  a(x) {
     a.push(x)
     return a[a.length-1]
  },
  b(x) {
     b.push(x)
     return b[b.length-1]
  }
})

```

**Comment by dy** [comment]
Interestingly "resetting" memory also crashes
```
let a = Object.create(Array.prototype), b = []

benchmark('Do closures cost anything?', function initialValue() {
  return Math.random()
}, {
  a(x) {
    if (a.length > 1e3) a.length = 0
     a.push(x)
     return a[a.length-1]
  },
  b(x) {
    if (b.length > 1e3) b.length = 0
     b.push(x)
     return b[b.length-1]
  }
})

```

**Comment by DavidSouther** [comment]
Works for me? 
<img width="820" alt="image" src="https://github.com/xpl/what-code-is-faster/assets/498712/f907a176-83a6-4d0f-839f-d738c25c959a">

For the non-length-resetting case, chrome throws an "Invalid Array Length" error:
  
<img width="776" alt="image" src="https://github.com/xpl/what-code-is-faster/assets/498712/32602f3d-a66b-4bbd-88b1-efb3162f19ce">

The range error is pushing with 50139473 elements in the array.

<img width="286" alt="image" src="https://github.com/xpl/what-code-is-faster/assets/498712/c1edf9ba-c6d6-4a04-88da-d6148187bea3">


> Chrome is up to date
> Version 120.0.6099.129 (Official Build) (arm64)

> Apple M1 Pro 32GB

**Comment by dy** [comment]
I remember that was code mistake
